"""Lightweight quick-look tools for HET instrumentation."""

from .config import QuicklookConfig
from .discovery import (
    ArchiveMember,
    DiscoveredObservation,
    RawFrameIdentity,
    discover_observations,
    inventory_members,
    parse_member_identity,
)
from .instrument import (
    Instrument,
    LRS2InstrumentComponent,
    PhysicalAmplifierIdentity,
    InstrumentTopology,
    lrs2_amplifier_tokens_for_channel,
    lrs2_component_for,
    lrs2_component_for_channel,
    lrs2_channel_for,
    lrs2_channel_for_identity,
    physical_identity_for,
    topology_for,
)
from .metadata import (
    ExposureMetadata,
    MetadataDisagreement,
    ObservationMetadata,
    exposure_metadata_from_headers,
    metadata_from_archive,
    metadata_from_header,
    metadata_from_members,
)
from .observation import Exposure, Observation, load_observation
from .raw import HeaderReadResult, RawFrameData, RawFrameLoader, load_frame
from .classification import (
    DEFAULT_STANDARD_STAR_CATALOG_SOURCE,
    ExposureClassification,
    ObjectIntent,
    STANDARD_STAR_ALIASES,
    STANDARD_STAR_NAMES,
    StandardStarCatalog,
    classify_exposure,
    normalize_standard_star_name,
    parse_object_intent,
)
from .topology import (
    ConfigurationResourceError,
    LRS2FiberPositionLoader,
    TopologyReference,
    VirusTopologyLoader,
    virus_orientation,
)
from .workflows import (
    AmplifierQuicklookEvidence,
    AmplifierTopologyResult,
    QuicklookDiagnostics,
    QuicklookError,
    LRS2AmplifierQuicklookEvidence,
    LRS2ChannelQuicklook,
    LRS2QuicklookSet,
    INSTRUMENT_SPATIAL_DEFAULTS,
    LRS2_SPATIAL_DEFAULTS,
    LRS2_STANDARD_FIDUCIAL,
    VIRUS_SPATIAL_DEFAULTS,
    VIRUS_STANDARD_FIDUCIAL,
    build_amplifier_topology,
    combine_lrs2_channel_products,
    combine_lrs2_channels,
    run_lrs2_channel_quicklooks,
    run_virus_ifu_quicklooks,
    VIRUSIFUQuicklookSet,
    VIRUSQuicklookSet,
    spatial_defaults_for,
)
from .highlevel import (
    QuicklookExposure,
    QuicklookIFU,
    QuicklookNight,
    QuicklookProduct,
    QuicklookSite,
)

__all__ = [
    "DiscoveredObservation",
    "ArchiveMember",
    "Instrument",
    "LRS2InstrumentComponent",
    "PhysicalAmplifierIdentity",
    "InstrumentTopology",
    "lrs2_amplifier_tokens_for_channel",
    "lrs2_component_for",
    "lrs2_component_for_channel",
    "ObservationMetadata",
    "ExposureMetadata",
    "MetadataDisagreement",
    "Observation",
    "Exposure",
    "QuicklookConfig",
    "QuicklookSite",
    "QuicklookNight",
    "QuicklookExposure",
    "QuicklookProduct",
    "QuicklookIFU",
    "RawFrameData",
    "HeaderReadResult",
    "RawFrameIdentity",
    "RawFrameLoader",
    "discover_observations",
    "inventory_members",
    "load_frame",
    "load_observation",
    "lrs2_channel_for",
    "lrs2_channel_for_identity",
    "metadata_from_archive",
    "exposure_metadata_from_headers",
    "metadata_from_header",
    "metadata_from_members",
    "parse_member_identity",
    "topology_for",
    "physical_identity_for",
    "ExposureClassification",
    "ObjectIntent",
    "STANDARD_STAR_NAMES",
    "STANDARD_STAR_ALIASES",
    "DEFAULT_STANDARD_STAR_CATALOG_SOURCE",
    "StandardStarCatalog",
    "classify_exposure",
    "normalize_standard_star_name",
    "parse_object_intent",
    "ConfigurationResourceError",
    "LRS2FiberPositionLoader",
    "TopologyReference",
    "VirusTopologyLoader",
    "virus_orientation",
    "LRS2_STANDARD_FIDUCIAL",
    "VIRUS_STANDARD_FIDUCIAL",
    "VIRUS_SPATIAL_DEFAULTS",
    "LRS2_SPATIAL_DEFAULTS",
    "INSTRUMENT_SPATIAL_DEFAULTS",
    "LRS2ChannelQuicklook",
    "LRS2AmplifierQuicklookEvidence",
    "LRS2QuicklookSet",
    "AmplifierQuicklookEvidence",
    "VIRUSIFUQuicklookSet",
    "VIRUSQuicklookSet",
    "AmplifierTopologyResult",
    "QuicklookDiagnostics",
    "QuicklookError",
    "build_amplifier_topology",
    "combine_lrs2_channel_products",
    "combine_lrs2_channels",
    "run_lrs2_channel_quicklooks",
    "run_virus_ifu_quicklooks",
    "spatial_defaults_for",
]

__version__ = "0.1.0"
